version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      test-tooling:
        patterns:
          - '@playwright/*'
          - '@axe-core/*'
          - 'eslint*'
          - 'prettier'
          - 'typescript*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
